/**
 * @module generators/context
 * @description Orchestrates assembly of CONTEXT.md by collecting output from
 * the structure, jsdoc, gherkin, and typescript parsers and writing the
 * result to the configured output file. Sections are conditionally included
 * based on config.context.sections flags. Does NOT perform any parsing
 * itself — delegates to the parsers/ modules.
 */

import { writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { existsSync } from 'node:fs';
import { BddWorkflowConfig } from '../config.js';
import { generateDirectoryTree } from './structure.js';
import { parseFeatureFiles, FeatureSummary } from '../parsers/gherkin.js';
import { extractModuleSummaries, ModuleSummary } from '../parsers/jsdoc.js';
import { extractPublicApi, ApiEntry } from '../parsers/typescript.js';

/**
 * Generate CONTEXT.md for the given configuration.
 *
 * Assembles up to five sections in order:
 * 1. Header (always)
 * 2. Overview (always — derived from package.json + src/index.ts @module)
 * 3. Directory Structure (when config.context.sections.structure is true)
 * 4. Module Summaries (when config.context.sections.moduleSummaries is true)
 * 5. Feature Summaries (when config.context.sections.featureSummaries is true)
 * 6. Public API (when config.context.sections.exports is true)
 *
 * @param config - Resolved bdd-workflow configuration
 * @returns Promise that resolves when CONTEXT.md has been written
 */
export async function generateContext(config: BddWorkflowConfig): Promise<void> {
  const sections: string[] = [];

  // Header — always included
  sections.push('# Project Context');
  sections.push(
    `> Auto-generated by \`npx bdd-workflow context\`. Do not edit manually.\n` +
    `> Last updated: ${new Date().toISOString()}`
  );

  // Overview — always included
  const overview = await buildOverview();
  sections.push(`## Overview\n\n${overview}`);

  // Directory Structure
  if (config.context.sections.structure) {
    const tree = await generateDirectoryTree(config);
    sections.push(`## Directory Structure\n\n\`\`\`\n${tree}\n\`\`\``);
  }

  // Module Summaries
  if (config.context.sections.moduleSummaries) {
    const modules = await extractModuleSummaries(config);
    const section = formatModulesSection(modules);
    if (section) sections.push(section);
  }

  // Feature Summaries
  if (config.context.sections.featureSummaries) {
    const features = await parseFeatureFiles(config);
    const section = formatFeaturesSection(features);
    if (section) sections.push(section);
  }

  // Public API
  if (config.context.sections.exports) {
    const api = await extractPublicApi(config);
    const section = formatApiSection(api);
    if (section) sections.push(section);
  }

  await writeFile(config.context.outputFile, sections.join('\n\n') + '\n');
}

/**
 * Build the Overview section from package.json description and src/index.ts @module comment.
 *
 * @returns Overview text string
 */
async function buildOverview(): Promise<string> {
  const parts: string[] = [];

  // Read package.json description
  const pkgPath = join(process.cwd(), 'package.json');
  if (existsSync(pkgPath)) {
    try {
      const pkgContent = await readFile(pkgPath, 'utf-8');
      const pkg = JSON.parse(pkgContent) as { name?: string; description?: string };
      if (pkg.description) {
        parts.push(pkg.description);
      } else if (pkg.name) {
        parts.push(`Package: ${pkg.name}`);
      }
    } catch {
      // Ignore parse errors
    }
  }

  return parts.join('\n\n') || '_No overview available._';
}

/**
 * Format the Modules section as a markdown table.
 *
 * @param modules - Array of module summaries
 * @returns Formatted markdown string, or empty string if no modules
 */
function formatModulesSection(modules: ModuleSummary[]): string {
  if (modules.length === 0) return '';

  const rows = modules.map(m => `| \`${m.filePath}\` | ${m.description} |`);
  return [
    '## Modules',
    '',
    '| File | Description |',
    '|------|-------------|',
    ...rows,
  ].join('\n');
}

/**
 * Format the Features section as grouped subsections.
 *
 * @param features - Array of feature summaries
 * @returns Formatted markdown string, or a fallback message section if empty
 */
function formatFeaturesSection(features: FeatureSummary[]): string {
  if (features.length === 0) {
    return '## Features\n\n_No feature files found._';
  }

  const lines: string[] = ['## Features'];
  for (const feature of features) {
    lines.push('');
    lines.push(`### ${feature.featureName} (\`${feature.filePath}\`)`);
    for (const scenario of feature.scenarios) {
      lines.push(`- Scenario: ${scenario}`);
    }
  }

  return lines.join('\n');
}

/**
 * Format the Public API section as grouped subsections with signature lists.
 *
 * @param api - Array of API entries
 * @returns Formatted markdown string, or empty string if no exports found
 */
function formatApiSection(api: ApiEntry[]): string {
  if (api.length === 0) return '';

  const lines: string[] = ['## Public API'];
  for (const entry of api) {
    lines.push('');
    lines.push(`### \`${entry.filePath}\``);
    for (const sig of entry.signatures) {
      lines.push(`- \`${sig}\``);
    }
  }

  return lines.join('\n');
}
