/**
 * @module generators/specs
 * @description Assembles SPECS.md — a human-readable behavioral specification
 * document derived from all Gherkin `.feature` files in the project.
 * Reuses the `parseFeatureFilesDetailed` parser from src/parsers/gherkin.ts,
 * formats full step text (keyword + text), feature descriptions, and scenario
 * tags, and appends a summary table. Does NOT abbreviate scenario outlines to
 * individual example rows — shows the outline template with `<placeholder>`
 * syntax instead. Does NOT write CONTEXT.md — that is handled by
 * src/generators/context.ts.
 */

import { writeFile } from 'node:fs/promises';
import { BddWorkflowConfig } from '../config.js';
import { parseFeatureFilesDetailed } from '../parsers/gherkin.js';

/**
 * Generate SPECS.md from all `.feature` files in the configured directory.
 *
 * Writes a formatted markdown document to `outputPath`. Each Feature becomes
 * an H2 section; each Scenario becomes an H3 with its full step text. A
 * summary table is appended at the end. Runs gracefully when no feature files
 * exist (writes an empty summary).
 *
 * @param config - Resolved bdd-workflow configuration
 * @param outputPath - Path to write SPECS.md (default: 'SPECS.md')
 */
export async function generateSpecs(
  config: BddWorkflowConfig,
  outputPath: string
): Promise<void> {
  const features = await parseFeatureFilesDetailed(config);
  const lines: string[] = [];

  // Header block
  lines.push('# Behavioral Specifications\n');
  lines.push(
    `> Auto-generated by \`npx bdd-workflow specs\`. Do not edit manually.\n` +
      `> Last updated: ${new Date().toISOString()}\n` +
      `>\n` +
      `> This document summarizes all behavioral specifications defined in \`${config.bdd.featuresDir}/\`.\n` +
      `> Each specification corresponds to a Gherkin \`.feature\` file.`
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const feature of features) {
    lines.push(`## ${feature.featureName}`);
    lines.push('');
    lines.push(`**File**: \`${feature.filePath}\``);
    lines.push('');

    if (feature.description.trim()) {
      lines.push(feature.description.trim());
      lines.push('');
    }

    for (const scenario of feature.scenarios) {
      lines.push(`### ${scenario.name}`);
      lines.push('');

      if (scenario.isOutline) {
        lines.push('*(Scenario Outline)*');
        lines.push('');
      }

      if (scenario.tags.length > 0) {
        lines.push(`*Tags: ${scenario.tags.join(', ')}*`);
        lines.push('');
      }

      for (const step of scenario.steps) {
        lines.push(`**${step.keyword}** ${step.text}`);
      }
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Feature | Scenarios |');
  lines.push('|---------|-----------|');

  let total = 0;
  for (const feature of features) {
    lines.push(`| ${feature.featureName} | ${feature.scenarios.length} |`);
    total += feature.scenarios.length;
  }
  lines.push(`| **Total** | **${total}** |`);
  lines.push('');

  await writeFile(outputPath, lines.join('\n'));
}
